name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - if: startsWith(github.ref, 'refs/tags/')
      - run: |
          # stretch-based image with Node 14
          docker buildx build \
            --build-arg RELEASE=stretch \
            --build-arg NODE=14 \
            --platform linux/arm,linux/amd64 \
            -t ghcr.io/variocube/debian-build:stretch \
            --push .

          # bullseye-based image with Node 18
          docker buildx build \
            --build-arg RELEASE=bullseye \
            --build-arg NODE=18 \
            --platform linux/arm,linux/amd64,linux/arm64 \
            -t ghcr.io/variocube/debian-build:bullseye \
            --push .

          # latest image is currently bullseye
          docker buildx build \
            --build-arg RELEASE=bullseye \
            --build-arg NODE=18 \
            --platform linux/arm,linux/amd64,linux/arm64 \
            -t ghcr.io/variocube/debian-build:latest \
            --push .
